spring:
  profiles: dev
  datasource:
    name: zh-admin
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat #监控统计拦截的filters
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test-security?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8 #基本属性
      username: root
      password: root
      initial-size: 1 #配置初始化大小/最小/最大
      min-idle: 1
      max-active: 20
      max-wait: 60000 #获取连接等待超时时间
      time-between-eviction-runs-millis: 60000 #间隔多久进行一次检测，检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 300000 #一个连接在池中最小生存的时间
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      max-pool-prepared-statement-per-connection-size: 20